 [nfs]
 3.82.194.239 ansible_ssh_user=ec2-user

[webservers]
18.212.27.160 ansible_ssh_user=ec2-user
52.207.184.220 ansible_ssh_user=ec2-user

[db]
44.204.26.61 ansible_ssh_user=ec2-user 

[lb]
18.204.215.198 ansible_ssh_user=ubuntu
