[nfs]
172.31.35.108 ansible_ssh_user=ec2-user

[webservers]
172.31.45.43 ansible_ssh_user=ec2-user
172.31.45.188 ansible_ssh_user=ec2-user

[db]
172.31.37.87 ansible_ssh_user=ec2-user 

[lb]
172.31.32.159 ansible_ssh_user=ubuntu
