[nfs]
172.31.91.72 ansible_ssh_user=ec2-user

[webservers]
172.31.95.216 ansible_ssh_user=ec2-user
172.31.86.43 ansible_ssh_user=ec2-user

[db]
172.31.88.111 ansible_ssh_user=ec2-user

[lb]
172.31.93.7 ansible_ssh_user=ubuntu