[nfs]
 172.31.27.224 ansible_ssh_user=ec2-user ansible_ssh_private_key_file=server.pem

[webservers]
 172.31.19.69 ansible_ssh_user=ec2-user ansible_ssh_private_key_file=server.pem
 172.31.25.58 ansible_ssh_user=ec2-user ansible_ssh_private_key_file=server.pem

[db]
 172.31.23.172 ansible_ssh_user=ec2-user ansible_ssh_private_key_file=server.pem

[lb]
172.31.91.254 ansible_ssh_user=ubuntu ansible_ssh_private_key_file=server.pem