[[nfs]
172.31.27.224 ansible_ssh_user=ec2-user

[webservers]
172.31.19.69 ansible_ssh_user=ec2-user
172.31.25.58 ansible_ssh_user=ec2-user

[db]
172.31.23.172 ansible_ssh_user=ec2-user 

[lb]
172.31.91.254 ansible_ssh_user=ubuntu
