---
- hosts: all
- name: Include dynamic variables
  tasks: null
  import_playbook: ../static-assignments/common.yml
  include: ../dynamic-assignments/env-vars.yml
  tag:
    - always
- hosts: webservers
- name: Webserver assignment
  import_playbook: ../static-assignments/webservers.yml
- hosts: db
- name: installing db
  import_playbook: ../static-assignments/db.yml
- hosts: lb
- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required
