---

- name: Include dynamic variables 
  hosts: all
  

#- name: import common file
 # import_playbook: ../static-assignments/common.yml
 # tags:
   # - always

- name: include env-vars file
  import_playbook: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: webservers
- name: Webserver assignment
  import_playbook: ../static-assignments/webservers.yml

#- hosts: db
#- name: installing db
#  import_playbook: ../static-assignments/db.yml

#- hosts: lb
#- name: Loadbalancers assignment
 # import_playbook: ../static-assignments/loadbalancers.yml
  #when: load_balancer_is_required 
