---
- name: Include dynamic variables 
  hosts: all

  import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- name: Webserver assignment
  import_playbook: ../static-assignments/webservers.yml

- name: installing db
  import_playbook: ../static-assignments/db.yml

- name: Loadbalancers assignment
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required 
